import Head from 'next/head';
import Button from 'components/atom/Button';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="max-w-screen-x mx-auto border min-h-screen flex items-center justify-center">
        <Button>Proceed to payment</Button>
      </div>
    </>
  );
}
