import Head from 'next/head';
import Button from 'components/atom/Button';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="max-w-screen-sm mx-auto border   bg-red-100 min-h-screen overflow-hidden">
        <div className="flex flex-col  space-y-5 ">
          <div className="p-10">
            <div className="w-16 h-16 rounded-full bg-white mb-2 flex justify-center items-center">
              <img src="/logo.svg" alt="" />
            </div>
            <h1 className="text-5xl text-white font-bold w-56">
              Food for Everyone
            </h1>
          </div>
          <div className="flex flex-col sm:items-center">
            <div className="flex justify-center relative">
              <img src="/person1.png" alt="" className="w-64" />
              <img src="/person2.png" alt="" className="w-64" />
            </div>
          </div>
          <div className="p-10 flex justify-center">
            <button className="w-full sm:w-96 self-center bg-white py-5 px-10 rounded-full font-bold text-primary">
              Get Started
            </button>
          </div>
        </div>
      </div>
    </>
  );
}
